apiVersion: v1
kind: Service
metadata:
  name: mandelbrot
  namespace: mandelbrot
  labels:
    app.kubernetes.io/name: mandelbrot
    app.kubernetes.io/part-of: trinity
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mandelbrot
  ports:
    - name: http
      port: 80
      targetPort: http
