apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: hello
  labels:
    app.kubernetes.io/name: hello
    app.kubernetes.io/part-of: trinity
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: hello
  ports:
    - name: http
      port: 80
      targetPort: http
