apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: trinity-disallow-privileged-containers
  annotations:
    policies.kyverno.io/title: Disallow Privileged Containers
    policies.kyverno.io/category: Trinity Baseline
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: disallow-privileged-containers
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - hello
                - mandelbrot
                - observability
                - secrets-demo
      validate:
        message: Privileged containers are not allowed in Trinity workload namespaces.
        pattern:
          spec:
            =(initContainers):
              - =(securityContext):
                  =(privileged): "false"
            containers:
              - =(securityContext):
                  =(privileged): "false"
