apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: provider-test-secret
  namespace: secrets-demo
  labels:
    app.kubernetes.io/name: secrets-demo
    app.kubernetes.io/part-of: trinity
    trinity.io/cloud: aws
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: provider-test-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: message
      remoteRef:
        key: trinity-dev-aws-secrets-demo-mg
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
