apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trinity-secrets-demo-aws
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/part-of: trinity
    trinity.io/cloud: aws
spec:
  project: trinity
  source:
    repoURL: https://github.com/maxgherman/trinity.git
    targetRevision: main
    path: platform/secrets-demo/overlays/aws
  destination:
    server: https://kubernetes.default.svc
    namespace: secrets-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
