apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: mandelbrot
    newName: us-central1-docker.pkg.dev/trinity-k8s/trinity-dev-gcp-mandelbrot/mandelbrot
    newTag: sha-35df206b6b96c88b3615cb75261091e65c1000c8
patches:
  - target:
      kind: Rollout
      name: mandelbrot
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: gcp
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: us-central1
