apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
  labels:
    app.kubernetes.io/name: secrets-demo
    app.kubernetes.io/part-of: trinity
    trinity.io/cloud: azure
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://trinity-dev-mg-kv.vault.azure.net
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
