apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
  labels:
    app.kubernetes.io/name: secrets-demo
    app.kubernetes.io/part-of: trinity
    trinity.io/cloud: gcp
spec:
  provider:
    gcpsm:
      projectID: trinity-k8s
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
