apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-traces
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: trinity
    app.kubernetes.io/component: traces
    trinity.io/cloud: azure
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: grafana-cloud-traces
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: endpoint
      remoteRef:
        key: trinity-dev-azure-grafana-cloud-traces-endpoint
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: username
      remoteRef:
        key: trinity-dev-azure-grafana-cloud-traces-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: password
      remoteRef:
        key: trinity-dev-azure-grafana-cloud-traces-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
