apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Rollout
      name: mandelbrot
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: azure
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: eastus
