apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: mandelbrot
    newName: trinitydevazureacr.azurecr.io/mandelbrot
    newTag: sha-7402835a5f8e272372444f14417234b60600f04b
patches:
  - target:
      kind: Rollout
      name: mandelbrot
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: azure
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: eastus
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: mandelbrot-registry
