apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-logs
  namespace: observability
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/part-of: trinity
    app.kubernetes.io/component: logs
    trinity.io/cloud: gcp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: grafana-cloud-logs
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: url
      remoteRef:
        key: trinity-dev-gcp-grafana-cloud-logs-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: username
      remoteRef:
        key: trinity-dev-gcp-grafana-cloud-logs-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: password
      remoteRef:
        key: trinity-dev-gcp-grafana-cloud-logs-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
