apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hello.yaml
  - rollouts.yaml
  - mandelbrot.yaml
  - secrets.yaml
  - secrets-demo.yaml
  - observability.yaml
  - policy-engine.yaml
  - policies.yaml
