apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: observability
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: trinity
    app.kubernetes.io/component: logs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki
  ports:
    - name: http
      port: 3100
      targetPort: http
