apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: observability
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/part-of: trinity
    app.kubernetes.io/component: logs
